POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1a29rbyIsImlkIjoiNjhhMWMzMDIyZDkwMmQ1ZTdhYWJjMDJjIiwiaWF0IjoxNzU1NTMxNjYwfQ.G38Qix9okCd_nO4fA3nJq-Jjej-Ui568qM2W2IjWJQA

{
  "title": "test blog",
  "author": "test author",
  "url": "link will be here",
  "likes": 5
}